# Generated by Django 4.2.7 on 2023-12-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementtemplate',
            name='advertisement_svg',
            field=models.FileField(blank=True, null=True, upload_to='advertisements/'),
        ),
    ]
