# Generated by Django 4.2.7 on 2023-12-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapi', '0002_advertisementtemplate_advertisement_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementtemplate',
            name='generated_image',
            field=models.ImageField(upload_to='generated_images/'),
        ),
    ]
