# Generated by Django 4.2.7 on 2023-12-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageapi', '0003_alter_advertisementtemplate_generated_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisementtemplate',
            name='advertisement_svg',
        ),
    ]
